### PR TITLE
Pull Releases feature

### PR DESCRIPTION
**Pull request by phillipahereza**
To get the releases feature, we would pull this branch into our master branch.

Related PR #7

### CODE REVIEW

**Comment by phillipahereza** [comment]
@kilemensi can I merge this into master?

**Comment by kilemensi** [comment]
Just a quick headsup @phillipahereza:
 
 `settings.py`: Ensure all template loaders and apps required are included, I at least see `admin` and `auth` apps are missing as well as `app_directories.Loader` is missing from template loaders.

 **Plan**: I believe if/when we merge into master, every deploy of every app (Takwimu, HURUmap-apps, etc.) which directly pulls from our `wazimap/master` will break. How are we going to handle this?

**Comment by kilemensi** [comment]
PS: Is this related to #7 or replaces it @phillipahereza? If it replaces it, please close #7.

**Comment by phillipahereza** [comment]
> Just a quick headsup @phillipahereza:
> 
> `settings.py`: Ensure all template loaders and apps required are included, I at least see `admin` and `auth` apps are missing as well as `app_directories.Loader` is missing from template loaders.
> 
> **Plan**: I believe if/when we merge into master, every deploy of every app (Takwimu, HURUmap-apps, etc.) which directly pulls from our `wazimap/master` will break. How are we going to handle this?

@kilemensi I think we shouldn't merge into master for now so as not to mess up Takwimu, what do you think @DavidLemayian

**Comment by kilemensi** [comment]
Since realistically we only have two repos (Takwimu & HURUmap-apps) @phillipahereza, my two cents are:

 i. We should first create PRs on Takwimu and HURUmap-apps using this branch,
 ii. Test those PRs and ensure they are ready to use Wazimap datasets and releases,
 iii. Merge this branch into `master`,
 iii. Merge PRs on Takwimu and HURUmap-apps (now pointing to `master`), and lasts,
 iv. Redeploy all apps

By the way, merge @OpenUpSA/wazimap `master` into this branch as well just to be completely up to date/make sure we don't diverge from it.

**Pull request merged**
